# Generated by Django 3.1.1 on 2020-09-28 08:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('constituen', models.CharField(blank=True, max_length=254, null=True)),
                ('county_nam', models.CharField(blank=True, max_length=254, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'municipality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('objectid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('fid_field', models.BigIntegerField(blank=True, db_column='fid_', null=True)),
                ('full_id', models.TextField(blank=True, null=True)),
                ('osm_id', models.TextField(blank=True, null=True)),
                ('osm_type', models.TextField(blank=True, null=True)),
                ('highway', models.TextField(blank=True, null=True)),
                ('lanes', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('surface', models.TextField(blank=True, null=True)),
                ('oneway', models.TextField(blank=True, null=True)),
                ('junction', models.TextField(blank=True, null=True)),
                ('bridge', models.TextField(blank=True, null=True)),
                ('layer', models.TextField(blank=True, null=True)),
                ('access', models.TextField(blank=True, null=True)),
                ('descriptio', models.TextField(blank=True, null=True)),
                ('maxspeed', models.TextField(blank=True, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('maintenanc', models.TextField(blank=True, null=True)),
                ('constructi', models.TextField(blank=True, null=True)),
                ('road_struc', models.TextField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('standard_s', models.TextField(blank=True, null=True)),
                ('start_poin', models.FloatField(blank=True, null=True)),
                ('endpoint', models.FloatField(blank=True, null=True)),
                ('material', models.TextField(blank=True, null=True)),
                ('contract_p', models.DateField(blank=True, null=True)),
                ('contractor', models.TextField(blank=True, null=True)),
                ('authority', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'road',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wards',
            fields=[
                ('objectid', models.FloatField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('const_nam', models.CharField(blank=True, max_length=50, null=True)),
                ('elec_area_field', models.CharField(blank=True, db_column='elec_area_', max_length=50, null=True)),
                ('local_auth', models.CharField(blank=True, max_length=50, null=True)),
                ('const_no', models.FloatField(blank=True, null=True)),
                ('county_nam', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'wards',
                'managed': False,
            },
        ),
    ]
