# Generated by Django 3.1.1 on 2020-10-26 16:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('report_type', models.CharField(choices=[('BP', 'Bump'), ('RD', 'Road Sign'), ('PH', 'PotHoles'), ('DG', 'Drainage')], max_length=50, verbose_name='Report Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('date', models.DateField(verbose_name='Reported On')),
                ('image', models.ImageField(upload_to='reports', verbose_name='Condition Media')),
            ],
            options={
                'verbose_name': 'RoadReport',
                'verbose_name_plural': 'RoadReports',
            },
        ),
    ]
