# Generated by Django 3.1.1 on 2021-01-04 09:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0003_auto_20201026_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bridges',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('road_no', models.CharField(blank=True, max_length=80, null=True)),
                ('bridge_typ', models.CharField(blank=True, max_length=80, null=True)),
                ('cross_typ', models.CharField(blank=True, max_length=80, null=True)),
                ('spstruct_m', models.CharField(blank=True, max_length=80, null=True)),
                ('spstruct_c', models.CharField(blank=True, max_length=80, null=True)),
                ('sbstruct_m', models.CharField(blank=True, max_length=80, null=True)),
                ('deck_c', models.CharField(blank=True, max_length=80, null=True)),
                ('stuct_typ', models.CharField(blank=True, max_length=80, null=True)),
                ('sbstruct_c', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'bridges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('road_no', models.CharField(blank=True, max_length=30, null=True)),
                ('contractor', models.CharField(blank=True, max_length=120, null=True)),
                ('prj_name', models.CharField(blank=True, max_length=120, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('conct_sum', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nature_dvp', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, max_length=120, null=True)),
                ('maint_type', models.CharField(blank=True, max_length=100, null=True)),
                ('funding', models.CharField(blank=True, max_length=100, null=True)),
                ('materials_field', models.CharField(blank=True, db_column='materials_', max_length=254, null=True)),
                ('developed_field', models.FloatField(blank=True, db_column='developed_', null=True)),
            ],
            options={
                'db_table': 'development',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoadCondition',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('road_no', models.CharField(blank=True, max_length=30, null=True)),
                ('rd_condtn', models.CharField(blank=True, max_length=100, null=True)),
                ('condition_field', models.FloatField(blank=True, db_column='condition_', null=True)),
            ],
            options={
                'db_table': 'road_condition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('lanes', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('surface', models.CharField(blank=True, max_length=254, null=True)),
                ('bridge', models.CharField(blank=True, max_length=254, null=True)),
                ('road_class', models.CharField(blank=True, max_length=27, null=True)),
                ('road_no', models.CharField(blank=True, max_length=30, null=True)),
                ('road_width', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('traffic', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('road_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('authority', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('road_lengt', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roads',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='roadreport',
            name='report_type',
            field=models.CharField(choices=[('BP', 'Bump'), ('RD', 'Road Sign'), ('PH', 'PotHoles'), ('DG', 'Drainage'), ('KB', 'Kerb'), ('RS', 'Road Sign'), ('BR', 'Bridges'), ('Ct', 'Culvert'), ('SD', 'Shoulders')], max_length=50, verbose_name='Report Type'),
        ),
    ]
