# Generated by Django 3.1.1 on 2020-10-01 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=13, verbose_name='ID Number')),
                ('profile_pic', models.ImageField(default='user3.jpg', upload_to='uploads', verbose_name='Profile Picture')),
                ('employee_status', models.CharField(choices=[('EN', 'Engineer'), ('MD', 'Director'), ('SU', 'Surveyor')], max_length=50, verbose_name='Employee Category')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('department', models.CharField(max_length=50, verbose_name='Department')),
                ('ward', models.CharField(max_length=50, verbose_name='Ward')),
                ('constituency', models.CharField(max_length=50, verbose_name='Constituency')),
                ('county', models.CharField(max_length=50, verbose_name='County')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
